<a href="https://colab.research.google.com/github/sanketdahiphale/DS_LAB/blob/main/Experiment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 matrix:")
print(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")

Original 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0


In [3]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 matrix:")
print(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print(f"\nDeterminant of the matrix: {determinant}")

# Attempt to compute the inverse of the matrix
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse of the matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError as e:
    print(f"\nError: {e}. The matrix is singular and does not have an inverse.")

Original 3x3 matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix: 0.0

Error: Singular matrix. The matrix is singular and does not have an inverse.


In [4]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constant vector B
B = np.array([10, 20])

print("Coefficient Matrix A:")
print(A)
print("\nConstant Vector B:")
print(B)

# Solve the system of linear equations Ax = B
try:
    solution = np.linalg.solve(A, B)
    print("\nSolution (x, y):")
    print(solution)
    print(f"\nTherefore, x = {solution[0]:.2f} and y = {solution[1]:.2f}")
except np.linalg.LinAlgError as e:
    print(f"\nError: {e}. The system might not have a unique solution.")

Coefficient Matrix A:
[[2 3]
 [4 5]]

Constant Vector B:
[10 20]

Solution (x, y):
[5. 0.]

Therefore, x = 5.00 and y = 0.00
